// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqfWdXllIjkRWp9VsXhK1cOAEusSb1zUs',
    appId: '1:3155941704:web:82d5c6d0b182908b313b7d',
    messagingSenderId: '3155941704',
    projectId: 'crudapp-16b68',
    authDomain: 'crudapp-16b68.firebaseapp.com',
    databaseURL: 'https://crudapp-16b68-default-rtdb.firebaseio.com',
    storageBucket: 'crudapp-16b68.appspot.com',
    measurementId: 'G-12WB4DQZY1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOql5Dj_-GyeGxtT_kV6qAmm6rDwTJviE',
    appId: '1:3155941704:android:3732e14f457e48e9313b7d',
    messagingSenderId: '3155941704',
    projectId: 'crudapp-16b68',
    databaseURL: 'https://crudapp-16b68-default-rtdb.firebaseio.com',
    storageBucket: 'crudapp-16b68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSu2-CusfISoDdIrZeZsPxpOXcsZxVb1M',
    appId: '1:3155941704:ios:ca84c9ed26f4fddb313b7d',
    messagingSenderId: '3155941704',
    projectId: 'crudapp-16b68',
    databaseURL: 'https://crudapp-16b68-default-rtdb.firebaseio.com',
    storageBucket: 'crudapp-16b68.appspot.com',
    iosClientId: '3155941704-foinq9do5qjq900tnt0efeqliei2sgp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSu2-CusfISoDdIrZeZsPxpOXcsZxVb1M',
    appId: '1:3155941704:ios:ca84c9ed26f4fddb313b7d',
    messagingSenderId: '3155941704',
    projectId: 'crudapp-16b68',
    databaseURL: 'https://crudapp-16b68-default-rtdb.firebaseio.com',
    storageBucket: 'crudapp-16b68.appspot.com',
    iosClientId: '3155941704-foinq9do5qjq900tnt0efeqliei2sgp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
